/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetBusinessesDocument,
    "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n": typeof types.GetBusinessDocument,
    "\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            isActive\n        }\n    }\n": typeof types.CreateBusinessDocument,
    "\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n        }\n    }\n": typeof types.UpdateBusinessDocument,
    "\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n": typeof types.DeleteBusinessDocument,
    "\n    query GetDrivers {\n        drivers {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            commissionPercentage\n            maxActiveOrders\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n": typeof types.GetDriversDocument,
    "\n    mutation AdminUpdateDriverSettings($driverId: ID!, $commissionPercentage: Float, $maxActiveOrders: Int) {\n        adminUpdateDriverSettings(driverId: $driverId, commissionPercentage: $commissionPercentage, maxActiveOrders: $maxActiveOrders) {\n            id\n            commissionPercentage\n            maxActiveOrders\n        }\n    }\n": typeof types.AdminUpdateDriverSettingsDocument,
    "\n    mutation AdminUpdateDriverLocation($driverId: ID!, $latitude: Float!, $longitude: Float!) {\n        adminUpdateDriverLocation(driverId: $driverId, latitude: $latitude, longitude: $longitude) {\n            id\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n        }\n    }\n": typeof types.AdminUpdateDriverLocationDocument,
    "\n    mutation UpdateDriverOnlineStatus($isOnline: Boolean!) {\n        updateDriverOnlineStatus(isOnline: $isOnline) {\n            id\n            isOnline\n            firstName\n            lastName\n        }\n    }\n": typeof types.UpdateDriverOnlineStatusDocument,
    "\n    subscription DriversUpdated {\n        driversUpdated {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n": typeof types.DriversUpdatedDocument,
    "\n    query GetStoreStatus {\n        getStoreStatus {\n            isStoreClosed\n            closedMessage\n        }\n    }\n": typeof types.GetStoreStatusDocument,
    "\n    mutation UpdateStoreStatus($input: UpdateStoreStatusInput!) {\n        updateStoreStatus(input: $input) {\n            isStoreClosed\n            closedMessage\n        }\n    }\n": typeof types.UpdateStoreStatusDocument,
    "\n    mutation SetMyPreferredLanguage($language: AppLanguage!) {\n        setMyPreferredLanguage(language: $language) {\n            id\n            preferredLanguage\n        }\n    }\n": typeof types.SetMyPreferredLanguageDocument,
    "\n    query GetNotificationCampaigns {\n        notificationCampaigns {\n            id\n            title\n            body\n            targetCount\n            sentCount\n            failedCount\n            status\n            createdAt\n            sentAt\n        }\n    }\n": typeof types.GetNotificationCampaignsDocument,
    "\n    mutation SendCampaign($id: ID!) {\n        sendCampaign(id: $id) {\n            id\n            status\n            sentCount\n            failedCount\n            sentAt\n        }\n    }\n": typeof types.SendCampaignDocument,
    "\n    mutation CreateCampaign($input: CreateCampaignInput!) {\n        createCampaign(input: $input) {\n            id\n            title\n            body\n            status\n        }\n    }\n": typeof types.CreateCampaignDocument,
    "\n    query GetSettlements(\n        $type: SettlementType\n        $status: SettlementStatus\n        $limit: Int\n        $offset: Int\n    ) {\n        settlements(type: $type, status: $status, limit: $limit, offset: $offset) {\n            id\n            type\n            driver {\n                id\n                firstName\n                lastName\n            }\n            business {\n                id\n                name\n            }\n            amount\n            status\n            paidAt\n            createdAt\n        }\n    }\n": typeof types.GetSettlementsDocument,
    "\n    mutation MarkSettlementAsPaid($settlementId: ID!) {\n        markSettlementAsPaid(settlementId: $settlementId) {\n            id\n            status\n            paidAt\n        }\n    }\n": typeof types.MarkSettlementAsPaidDocument,
    "\n    mutation RegisterDeviceToken($input: RegisterDeviceTokenInput!) {\n        registerDeviceToken(input: $input)\n    }\n": typeof types.RegisterDeviceTokenDocument,
    "\n    mutation UnregisterDeviceToken($token: String!) {\n        unregisterDeviceToken(token: $token)\n    }\n": typeof types.UnregisterDeviceTokenDocument,
    "\n    mutation TrackPushTelemetry($input: TrackPushTelemetryInput!) {\n        trackPushTelemetry(input: $input)\n    }\n": typeof types.TrackPushTelemetryDocument,
    "\n    query GetOrders {\n        orders(limit: 200) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n": typeof types.GetOrderDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            status\n        }\n    }\n": typeof types.UpdateOrderStatusDocument,
    "\n    mutation StartPreparing($id: ID!, $preparationMinutes: Int!) {\n        startPreparing(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n        }\n    }\n": typeof types.StartPreparingDocument,
    "\n    mutation UpdatePreparationTime($id: ID!, $preparationMinutes: Int!) {\n        updatePreparationTime(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            preparationMinutes\n            estimatedReadyAt\n        }\n    }\n": typeof types.UpdatePreparationTimeDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n": typeof types.CancelOrderDocument,
    "\n    mutation AssignDriverToOrder($id: ID!, $driverId: ID) {\n        assignDriverToOrder(id: $id, driverId: $driverId) {\n            id\n            driver {\n                id\n                firstName\n                lastName\n            }\n            status\n        }\n    }\n": typeof types.AssignDriverToOrderDocument,
    "\n    mutation CreateTestOrder {\n        createTestOrder {\n            id\n            status\n            totalPrice\n        }\n    }\n": typeof types.CreateTestOrderDocument,
    "\n    subscription AllOrdersUpdated {\n        allOrdersUpdated {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    phoneNumber\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n": typeof types.AllOrdersUpdatedDocument,
    "\n    query GetUsers {\n        users(limit: 500) {\n            id\n            email\n            firstName\n            lastName\n            role\n            phoneNumber\n            address\n            adminNote\n            flagColor\n            permissions\n            business {\n                id\n                name\n            }\n        }\n    }\n": typeof types.GetUsersDocument,
    "\n    query UserBehavior($userId: ID!) {\n        userBehavior(userId: $userId) {\n            userId\n            totalOrders\n            deliveredOrders\n            cancelledOrders\n            totalSpend\n            avgOrderValue\n            firstOrderAt\n            lastOrderAt\n            lastDeliveredAt\n        }\n    }\n": typeof types.UserBehaviorDocument,
    "\n    mutation CreateUser(\n        $email: String!\n        $password: String!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        createUser(\n            input: {\n                email: $email\n                password: $password\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                role\n                businessId\n            }\n            message\n        }\n    }\n": typeof types.CreateUserDocument,
    "\n    mutation UpdateUser(\n        $id: ID!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        updateUser(\n            input: {\n                id: $id\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            id\n            email\n            firstName\n            lastName\n            role\n        }\n    }\n": typeof types.UpdateUserDocument,
    "\n    mutation DeleteUser($id: ID!) {\n        deleteUser(id: $id)\n    }\n": typeof types.DeleteUserDocument,
    "\n    mutation UpdateUserNote($userId: ID!, $note: String, $flagColor: String) {\n        updateUserNote(userId: $userId, note: $note, flagColor: $flagColor) {\n            id\n            adminNote\n            flagColor\n        }\n    }\n": typeof types.UpdateUserNoteDocument,
    "\n    mutation SetUserPermissions($userId: ID!, $permissions: [UserPermission!]!) {\n        setUserPermissions(userId: $userId, permissions: $permissions) {\n            id\n            permissions\n        }\n    }\n": typeof types.SetUserPermissionsDocument,
};
const documents: Documents = {
    "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetBusinessesDocument,
    "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n": types.GetBusinessDocument,
    "\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            isActive\n        }\n    }\n": types.CreateBusinessDocument,
    "\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n        }\n    }\n": types.UpdateBusinessDocument,
    "\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n": types.DeleteBusinessDocument,
    "\n    query GetDrivers {\n        drivers {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            commissionPercentage\n            maxActiveOrders\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n": types.GetDriversDocument,
    "\n    mutation AdminUpdateDriverSettings($driverId: ID!, $commissionPercentage: Float, $maxActiveOrders: Int) {\n        adminUpdateDriverSettings(driverId: $driverId, commissionPercentage: $commissionPercentage, maxActiveOrders: $maxActiveOrders) {\n            id\n            commissionPercentage\n            maxActiveOrders\n        }\n    }\n": types.AdminUpdateDriverSettingsDocument,
    "\n    mutation AdminUpdateDriverLocation($driverId: ID!, $latitude: Float!, $longitude: Float!) {\n        adminUpdateDriverLocation(driverId: $driverId, latitude: $latitude, longitude: $longitude) {\n            id\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n        }\n    }\n": types.AdminUpdateDriverLocationDocument,
    "\n    mutation UpdateDriverOnlineStatus($isOnline: Boolean!) {\n        updateDriverOnlineStatus(isOnline: $isOnline) {\n            id\n            isOnline\n            firstName\n            lastName\n        }\n    }\n": types.UpdateDriverOnlineStatusDocument,
    "\n    subscription DriversUpdated {\n        driversUpdated {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n": types.DriversUpdatedDocument,
    "\n    query GetStoreStatus {\n        getStoreStatus {\n            isStoreClosed\n            closedMessage\n        }\n    }\n": types.GetStoreStatusDocument,
    "\n    mutation UpdateStoreStatus($input: UpdateStoreStatusInput!) {\n        updateStoreStatus(input: $input) {\n            isStoreClosed\n            closedMessage\n        }\n    }\n": types.UpdateStoreStatusDocument,
    "\n    mutation SetMyPreferredLanguage($language: AppLanguage!) {\n        setMyPreferredLanguage(language: $language) {\n            id\n            preferredLanguage\n        }\n    }\n": types.SetMyPreferredLanguageDocument,
    "\n    query GetNotificationCampaigns {\n        notificationCampaigns {\n            id\n            title\n            body\n            targetCount\n            sentCount\n            failedCount\n            status\n            createdAt\n            sentAt\n        }\n    }\n": types.GetNotificationCampaignsDocument,
    "\n    mutation SendCampaign($id: ID!) {\n        sendCampaign(id: $id) {\n            id\n            status\n            sentCount\n            failedCount\n            sentAt\n        }\n    }\n": types.SendCampaignDocument,
    "\n    mutation CreateCampaign($input: CreateCampaignInput!) {\n        createCampaign(input: $input) {\n            id\n            title\n            body\n            status\n        }\n    }\n": types.CreateCampaignDocument,
    "\n    query GetSettlements(\n        $type: SettlementType\n        $status: SettlementStatus\n        $limit: Int\n        $offset: Int\n    ) {\n        settlements(type: $type, status: $status, limit: $limit, offset: $offset) {\n            id\n            type\n            driver {\n                id\n                firstName\n                lastName\n            }\n            business {\n                id\n                name\n            }\n            amount\n            status\n            paidAt\n            createdAt\n        }\n    }\n": types.GetSettlementsDocument,
    "\n    mutation MarkSettlementAsPaid($settlementId: ID!) {\n        markSettlementAsPaid(settlementId: $settlementId) {\n            id\n            status\n            paidAt\n        }\n    }\n": types.MarkSettlementAsPaidDocument,
    "\n    mutation RegisterDeviceToken($input: RegisterDeviceTokenInput!) {\n        registerDeviceToken(input: $input)\n    }\n": types.RegisterDeviceTokenDocument,
    "\n    mutation UnregisterDeviceToken($token: String!) {\n        unregisterDeviceToken(token: $token)\n    }\n": types.UnregisterDeviceTokenDocument,
    "\n    mutation TrackPushTelemetry($input: TrackPushTelemetryInput!) {\n        trackPushTelemetry(input: $input)\n    }\n": types.TrackPushTelemetryDocument,
    "\n    query GetOrders {\n        orders(limit: 200) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n": types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n": types.GetOrderDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            status\n        }\n    }\n": types.UpdateOrderStatusDocument,
    "\n    mutation StartPreparing($id: ID!, $preparationMinutes: Int!) {\n        startPreparing(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n        }\n    }\n": types.StartPreparingDocument,
    "\n    mutation UpdatePreparationTime($id: ID!, $preparationMinutes: Int!) {\n        updatePreparationTime(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            preparationMinutes\n            estimatedReadyAt\n        }\n    }\n": types.UpdatePreparationTimeDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n": types.CancelOrderDocument,
    "\n    mutation AssignDriverToOrder($id: ID!, $driverId: ID) {\n        assignDriverToOrder(id: $id, driverId: $driverId) {\n            id\n            driver {\n                id\n                firstName\n                lastName\n            }\n            status\n        }\n    }\n": types.AssignDriverToOrderDocument,
    "\n    mutation CreateTestOrder {\n        createTestOrder {\n            id\n            status\n            totalPrice\n        }\n    }\n": types.CreateTestOrderDocument,
    "\n    subscription AllOrdersUpdated {\n        allOrdersUpdated {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    phoneNumber\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n": types.AllOrdersUpdatedDocument,
    "\n    query GetUsers {\n        users(limit: 500) {\n            id\n            email\n            firstName\n            lastName\n            role\n            phoneNumber\n            address\n            adminNote\n            flagColor\n            permissions\n            business {\n                id\n                name\n            }\n        }\n    }\n": types.GetUsersDocument,
    "\n    query UserBehavior($userId: ID!) {\n        userBehavior(userId: $userId) {\n            userId\n            totalOrders\n            deliveredOrders\n            cancelledOrders\n            totalSpend\n            avgOrderValue\n            firstOrderAt\n            lastOrderAt\n            lastDeliveredAt\n        }\n    }\n": types.UserBehaviorDocument,
    "\n    mutation CreateUser(\n        $email: String!\n        $password: String!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        createUser(\n            input: {\n                email: $email\n                password: $password\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                role\n                businessId\n            }\n            message\n        }\n    }\n": types.CreateUserDocument,
    "\n    mutation UpdateUser(\n        $id: ID!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        updateUser(\n            input: {\n                id: $id\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            id\n            email\n            firstName\n            lastName\n            role\n        }\n    }\n": types.UpdateUserDocument,
    "\n    mutation DeleteUser($id: ID!) {\n        deleteUser(id: $id)\n    }\n": types.DeleteUserDocument,
    "\n    mutation UpdateUserNote($userId: ID!, $note: String, $flagColor: String) {\n        updateUserNote(userId: $userId, note: $note, flagColor: $flagColor) {\n            id\n            adminNote\n            flagColor\n        }\n    }\n": types.UpdateUserNoteDocument,
    "\n    mutation SetUserPermissions($userId: ID!, $permissions: [UserPermission!]!) {\n        setUserPermissions(userId: $userId, permissions: $permissions) {\n            id\n            permissions\n        }\n    }\n": types.SetUserPermissionsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            phoneNumber\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            schedule {\n                id\n                dayOfWeek\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            isActive\n        }\n    }\n"): (typeof documents)["\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            isActive\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n"): (typeof documents)["\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetDrivers {\n        drivers {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            commissionPercentage\n            maxActiveOrders\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetDrivers {\n        drivers {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            commissionPercentage\n            maxActiveOrders\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation AdminUpdateDriverSettings($driverId: ID!, $commissionPercentage: Float, $maxActiveOrders: Int) {\n        adminUpdateDriverSettings(driverId: $driverId, commissionPercentage: $commissionPercentage, maxActiveOrders: $maxActiveOrders) {\n            id\n            commissionPercentage\n            maxActiveOrders\n        }\n    }\n"): (typeof documents)["\n    mutation AdminUpdateDriverSettings($driverId: ID!, $commissionPercentage: Float, $maxActiveOrders: Int) {\n        adminUpdateDriverSettings(driverId: $driverId, commissionPercentage: $commissionPercentage, maxActiveOrders: $maxActiveOrders) {\n            id\n            commissionPercentage\n            maxActiveOrders\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation AdminUpdateDriverLocation($driverId: ID!, $latitude: Float!, $longitude: Float!) {\n        adminUpdateDriverLocation(driverId: $driverId, latitude: $latitude, longitude: $longitude) {\n            id\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation AdminUpdateDriverLocation($driverId: ID!, $latitude: Float!, $longitude: Float!) {\n        adminUpdateDriverLocation(driverId: $driverId, latitude: $latitude, longitude: $longitude) {\n            id\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateDriverOnlineStatus($isOnline: Boolean!) {\n        updateDriverOnlineStatus(isOnline: $isOnline) {\n            id\n            isOnline\n            firstName\n            lastName\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateDriverOnlineStatus($isOnline: Boolean!) {\n        updateDriverOnlineStatus(isOnline: $isOnline) {\n            id\n            isOnline\n            firstName\n            lastName\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription DriversUpdated {\n        driversUpdated {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n"): (typeof documents)["\n    subscription DriversUpdated {\n        driversUpdated {\n            id\n            email\n            firstName\n            lastName\n            role\n            imageUrl\n            phoneNumber\n            driverLocation {\n                latitude\n                longitude\n                address\n            }\n            driverLocationUpdatedAt\n            driverConnection {\n                onlinePreference\n                connectionStatus\n                lastHeartbeatAt\n                lastLocationUpdate\n                disconnectedAt\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetStoreStatus {\n        getStoreStatus {\n            isStoreClosed\n            closedMessage\n        }\n    }\n"): (typeof documents)["\n    query GetStoreStatus {\n        getStoreStatus {\n            isStoreClosed\n            closedMessage\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateStoreStatus($input: UpdateStoreStatusInput!) {\n        updateStoreStatus(input: $input) {\n            isStoreClosed\n            closedMessage\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateStoreStatus($input: UpdateStoreStatusInput!) {\n        updateStoreStatus(input: $input) {\n            isStoreClosed\n            closedMessage\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SetMyPreferredLanguage($language: AppLanguage!) {\n        setMyPreferredLanguage(language: $language) {\n            id\n            preferredLanguage\n        }\n    }\n"): (typeof documents)["\n    mutation SetMyPreferredLanguage($language: AppLanguage!) {\n        setMyPreferredLanguage(language: $language) {\n            id\n            preferredLanguage\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetNotificationCampaigns {\n        notificationCampaigns {\n            id\n            title\n            body\n            targetCount\n            sentCount\n            failedCount\n            status\n            createdAt\n            sentAt\n        }\n    }\n"): (typeof documents)["\n    query GetNotificationCampaigns {\n        notificationCampaigns {\n            id\n            title\n            body\n            targetCount\n            sentCount\n            failedCount\n            status\n            createdAt\n            sentAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SendCampaign($id: ID!) {\n        sendCampaign(id: $id) {\n            id\n            status\n            sentCount\n            failedCount\n            sentAt\n        }\n    }\n"): (typeof documents)["\n    mutation SendCampaign($id: ID!) {\n        sendCampaign(id: $id) {\n            id\n            status\n            sentCount\n            failedCount\n            sentAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateCampaign($input: CreateCampaignInput!) {\n        createCampaign(input: $input) {\n            id\n            title\n            body\n            status\n        }\n    }\n"): (typeof documents)["\n    mutation CreateCampaign($input: CreateCampaignInput!) {\n        createCampaign(input: $input) {\n            id\n            title\n            body\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetSettlements(\n        $type: SettlementType\n        $status: SettlementStatus\n        $limit: Int\n        $offset: Int\n    ) {\n        settlements(type: $type, status: $status, limit: $limit, offset: $offset) {\n            id\n            type\n            driver {\n                id\n                firstName\n                lastName\n            }\n            business {\n                id\n                name\n            }\n            amount\n            status\n            paidAt\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    query GetSettlements(\n        $type: SettlementType\n        $status: SettlementStatus\n        $limit: Int\n        $offset: Int\n    ) {\n        settlements(type: $type, status: $status, limit: $limit, offset: $offset) {\n            id\n            type\n            driver {\n                id\n                firstName\n                lastName\n            }\n            business {\n                id\n                name\n            }\n            amount\n            status\n            paidAt\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation MarkSettlementAsPaid($settlementId: ID!) {\n        markSettlementAsPaid(settlementId: $settlementId) {\n            id\n            status\n            paidAt\n        }\n    }\n"): (typeof documents)["\n    mutation MarkSettlementAsPaid($settlementId: ID!) {\n        markSettlementAsPaid(settlementId: $settlementId) {\n            id\n            status\n            paidAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RegisterDeviceToken($input: RegisterDeviceTokenInput!) {\n        registerDeviceToken(input: $input)\n    }\n"): (typeof documents)["\n    mutation RegisterDeviceToken($input: RegisterDeviceTokenInput!) {\n        registerDeviceToken(input: $input)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UnregisterDeviceToken($token: String!) {\n        unregisterDeviceToken(token: $token)\n    }\n"): (typeof documents)["\n    mutation UnregisterDeviceToken($token: String!) {\n        unregisterDeviceToken(token: $token)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation TrackPushTelemetry($input: TrackPushTelemetryInput!) {\n        trackPushTelemetry(input: $input)\n    }\n"): (typeof documents)["\n    mutation TrackPushTelemetry($input: TrackPushTelemetryInput!) {\n        trackPushTelemetry(input: $input)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrders {\n        orders(limit: 200) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrders {\n        orders(limit: 200) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    phoneNumber\n                    businessType\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            status\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation StartPreparing($id: ID!, $preparationMinutes: Int!) {\n        startPreparing(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n        }\n    }\n"): (typeof documents)["\n    mutation StartPreparing($id: ID!, $preparationMinutes: Int!) {\n        startPreparing(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdatePreparationTime($id: ID!, $preparationMinutes: Int!) {\n        updatePreparationTime(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            preparationMinutes\n            estimatedReadyAt\n        }\n    }\n"): (typeof documents)["\n    mutation UpdatePreparationTime($id: ID!, $preparationMinutes: Int!) {\n        updatePreparationTime(id: $id, preparationMinutes: $preparationMinutes) {\n            id\n            preparationMinutes\n            estimatedReadyAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n"): (typeof documents)["\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation AssignDriverToOrder($id: ID!, $driverId: ID) {\n        assignDriverToOrder(id: $id, driverId: $driverId) {\n            id\n            driver {\n                id\n                firstName\n                lastName\n            }\n            status\n        }\n    }\n"): (typeof documents)["\n    mutation AssignDriverToOrder($id: ID!, $driverId: ID) {\n        assignDriverToOrder(id: $id, driverId: $driverId) {\n            id\n            driver {\n                id\n                firstName\n                lastName\n            }\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateTestOrder {\n        createTestOrder {\n            id\n            status\n            totalPrice\n        }\n    }\n"): (typeof documents)["\n    mutation CreateTestOrder {\n        createTestOrder {\n            id\n            status\n            totalPrice\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription AllOrdersUpdated {\n        allOrdersUpdated {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    phoneNumber\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    subscription AllOrdersUpdated {\n        allOrdersUpdated {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            preparationMinutes\n            estimatedReadyAt\n            preparingAt\n            user {\n                id\n                firstName\n                lastName\n                email\n                address\n                phoneNumber\n            }\n            driver {\n                id\n                firstName\n                lastName\n                email\n                phoneNumber\n            }\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    phoneNumber\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    unitPrice\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetUsers {\n        users(limit: 500) {\n            id\n            email\n            firstName\n            lastName\n            role\n            phoneNumber\n            address\n            adminNote\n            flagColor\n            permissions\n            business {\n                id\n                name\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetUsers {\n        users(limit: 500) {\n            id\n            email\n            firstName\n            lastName\n            role\n            phoneNumber\n            address\n            adminNote\n            flagColor\n            permissions\n            business {\n                id\n                name\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query UserBehavior($userId: ID!) {\n        userBehavior(userId: $userId) {\n            userId\n            totalOrders\n            deliveredOrders\n            cancelledOrders\n            totalSpend\n            avgOrderValue\n            firstOrderAt\n            lastOrderAt\n            lastDeliveredAt\n        }\n    }\n"): (typeof documents)["\n    query UserBehavior($userId: ID!) {\n        userBehavior(userId: $userId) {\n            userId\n            totalOrders\n            deliveredOrders\n            cancelledOrders\n            totalSpend\n            avgOrderValue\n            firstOrderAt\n            lastOrderAt\n            lastDeliveredAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateUser(\n        $email: String!\n        $password: String!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        createUser(\n            input: {\n                email: $email\n                password: $password\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                role\n                businessId\n            }\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation CreateUser(\n        $email: String!\n        $password: String!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        createUser(\n            input: {\n                email: $email\n                password: $password\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                role\n                businessId\n            }\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateUser(\n        $id: ID!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        updateUser(\n            input: {\n                id: $id\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            id\n            email\n            firstName\n            lastName\n            role\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateUser(\n        $id: ID!\n        $firstName: String!\n        $lastName: String!\n        $role: UserRole!\n        $businessId: ID\n    ) {\n        updateUser(\n            input: {\n                id: $id\n                firstName: $firstName\n                lastName: $lastName\n                role: $role\n                businessId: $businessId\n            }\n        ) {\n            id\n            email\n            firstName\n            lastName\n            role\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteUser($id: ID!) {\n        deleteUser(id: $id)\n    }\n"): (typeof documents)["\n    mutation DeleteUser($id: ID!) {\n        deleteUser(id: $id)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateUserNote($userId: ID!, $note: String, $flagColor: String) {\n        updateUserNote(userId: $userId, note: $note, flagColor: $flagColor) {\n            id\n            adminNote\n            flagColor\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateUserNote($userId: ID!, $note: String, $flagColor: String) {\n        updateUserNote(userId: $userId, note: $note, flagColor: $flagColor) {\n            id\n            adminNote\n            flagColor\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SetUserPermissions($userId: ID!, $permissions: [UserPermission!]!) {\n        setUserPermissions(userId: $userId, permissions: $permissions) {\n            id\n            permissions\n        }\n    }\n"): (typeof documents)["\n    mutation SetUserPermissions($userId: ID!, $permissions: [UserPermission!]!) {\n        setUserPermissions(userId: $userId, permissions: $permissions) {\n            id\n            permissions\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;