/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetBusinessesDocument,
    "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetBusinessDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.UpdateOrderStatusDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.CancelOrderDocument,
    "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrderDocument,
    "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersByStatusDocument,
    "\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n": typeof types.OrderStatusUpdatedDocument,
    "\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetProductsDocument,
    "\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetProductDocument,
};
const documents: Documents = {
    "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetBusinessesDocument,
    "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetBusinessDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.UpdateOrderStatusDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.CancelOrderDocument,
    "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrderDocument,
    "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrdersByStatusDocument,
    "\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n": types.OrderStatusUpdatedDocument,
    "\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetProductsDocument,
    "\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetProductDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n"): (typeof documents)["\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            createdAt\n            updatedAt\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;