/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    mutation InitiateSignup($input: InitiateSignupInput!) {\n        initiateSignup(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n": typeof types.InitiateSignupDocument,
    "\n    mutation Login($input: LoginInput!) {\n        login(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n": typeof types.LoginDocument,
    "\n    query Me {\n        me {\n            id\n            email\n            firstName\n            lastName\n            signupStep\n            emailVerified\n            phoneVerified\n            phoneNumber\n            address\n            role\n        }\n    }\n": typeof types.MeDocument,
    "\n    mutation ResendEmailVerification {\n        resendEmailVerification {\n            userId\n            currentStep\n            message\n        }\n    }\n": typeof types.ResendEmailVerificationDocument,
    "\n    mutation SubmitPhoneNumber($input: SubmitPhoneNumberInput!) {\n        submitPhoneNumber(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n": typeof types.SubmitPhoneNumberDocument,
    "\n    mutation VerifyEmail($input: VerifyEmailInput!) {\n        verifyEmail(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n": typeof types.VerifyEmailDocument,
    "\n    mutation VerifyPhone($input: VerifyPhoneInput!) {\n        verifyPhone(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n": typeof types.VerifyPhoneDocument,
    "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetBusinessesDocument,
    "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetBusinessDocument,
    "\n    mutation CreateOrder($input: CreateOrderInput!) {\n        createOrder(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    isActive\n                    isOpen\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.CreateOrderDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.UpdateOrderStatusDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.CancelOrderDocument,
    "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                    createdAt\n                    updatedAt\n                    isOpen\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrderDocument,
    "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersByStatusDocument,
    "\n    query UncompletedOrders {\n        uncompletedOrders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.UncompletedOrdersDocument,
    "\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n": typeof types.OrderStatusUpdatedDocument,
    "\n    subscription UserOrdersUpdated($input: SubscriptionInput!) {\n        userOrdersUpdated(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.UserOrdersUpdatedDocument,
    "\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetProductsDocument,
    "\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.GetProductDocument,
    "\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n    }\n": typeof types.ProductCategoriesDocument,
    "\n    query ProductSubcategoriesByBusiness($businessId: ID!) {\n        productSubcategoriesByBusiness(businessId: $businessId) {\n            id\n            categoryId\n            name\n        }\n    }\n": typeof types.ProductSubcategoriesByBusinessDocument,
    "\n    query ValidatePromotions($cart: CartContextInput!, $manualCode: String) {\n        validatePromotions(cart: $cart, manualCode: $manualCode) {\n            totalDiscount\n            freeDeliveryApplied\n            finalSubtotal\n            finalDeliveryPrice\n            finalTotal\n            promotions {\n                id\n                name\n                code\n                type\n                target\n                appliedAmount\n                freeDelivery\n                priority\n            }\n        }\n    }\n": typeof types.ValidatePromotionsDocument,
};
const documents: Documents = {
    "\n    mutation InitiateSignup($input: InitiateSignupInput!) {\n        initiateSignup(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n": types.InitiateSignupDocument,
    "\n    mutation Login($input: LoginInput!) {\n        login(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n": types.LoginDocument,
    "\n    query Me {\n        me {\n            id\n            email\n            firstName\n            lastName\n            signupStep\n            emailVerified\n            phoneVerified\n            phoneNumber\n            address\n            role\n        }\n    }\n": types.MeDocument,
    "\n    mutation ResendEmailVerification {\n        resendEmailVerification {\n            userId\n            currentStep\n            message\n        }\n    }\n": types.ResendEmailVerificationDocument,
    "\n    mutation SubmitPhoneNumber($input: SubmitPhoneNumberInput!) {\n        submitPhoneNumber(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n": types.SubmitPhoneNumberDocument,
    "\n    mutation VerifyEmail($input: VerifyEmailInput!) {\n        verifyEmail(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n": types.VerifyEmailDocument,
    "\n    mutation VerifyPhone($input: VerifyPhoneInput!) {\n        verifyPhone(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n": types.VerifyPhoneDocument,
    "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetBusinessesDocument,
    "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetBusinessDocument,
    "\n    mutation CreateOrder($input: CreateOrderInput!) {\n        createOrder(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    isActive\n                    isOpen\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.CreateOrderDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.UpdateOrderStatusDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.CancelOrderDocument,
    "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                    createdAt\n                    updatedAt\n                    isOpen\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrderDocument,
    "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrdersByStatusDocument,
    "\n    query UncompletedOrders {\n        uncompletedOrders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.UncompletedOrdersDocument,
    "\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n": types.OrderStatusUpdatedDocument,
    "\n    subscription UserOrdersUpdated($input: SubscriptionInput!) {\n        userOrdersUpdated(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.UserOrdersUpdatedDocument,
    "\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetProductsDocument,
    "\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n": types.GetProductDocument,
    "\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n    }\n": types.ProductCategoriesDocument,
    "\n    query ProductSubcategoriesByBusiness($businessId: ID!) {\n        productSubcategoriesByBusiness(businessId: $businessId) {\n            id\n            categoryId\n            name\n        }\n    }\n": types.ProductSubcategoriesByBusinessDocument,
    "\n    query ValidatePromotions($cart: CartContextInput!, $manualCode: String) {\n        validatePromotions(cart: $cart, manualCode: $manualCode) {\n            totalDiscount\n            freeDeliveryApplied\n            finalSubtotal\n            finalDeliveryPrice\n            finalTotal\n            promotions {\n                id\n                name\n                code\n                type\n                target\n                appliedAmount\n                freeDelivery\n                priority\n            }\n        }\n    }\n": types.ValidatePromotionsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InitiateSignup($input: InitiateSignupInput!) {\n        initiateSignup(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation InitiateSignup($input: InitiateSignupInput!) {\n        initiateSignup(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation Login($input: LoginInput!) {\n        login(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation Login($input: LoginInput!) {\n        login(input: $input) {\n            token\n            user {\n                id\n                email\n                firstName\n                lastName\n                signupStep\n                emailVerified\n                phoneVerified\n                phoneNumber\n                role\n            }\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query Me {\n        me {\n            id\n            email\n            firstName\n            lastName\n            signupStep\n            emailVerified\n            phoneVerified\n            phoneNumber\n            address\n            role\n        }\n    }\n"): (typeof documents)["\n    query Me {\n        me {\n            id\n            email\n            firstName\n            lastName\n            signupStep\n            emailVerified\n            phoneVerified\n            phoneNumber\n            address\n            role\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation ResendEmailVerification {\n        resendEmailVerification {\n            userId\n            currentStep\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation ResendEmailVerification {\n        resendEmailVerification {\n            userId\n            currentStep\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SubmitPhoneNumber($input: SubmitPhoneNumberInput!) {\n        submitPhoneNumber(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation SubmitPhoneNumber($input: SubmitPhoneNumberInput!) {\n        submitPhoneNumber(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation VerifyEmail($input: VerifyEmailInput!) {\n        verifyEmail(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation VerifyEmail($input: VerifyEmailInput!) {\n        verifyEmail(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation VerifyPhone($input: VerifyPhoneInput!) {\n        verifyPhone(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation VerifyPhone($input: VerifyPhoneInput!) {\n        verifyPhone(input: $input) {\n            userId\n            currentStep\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetBusinesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetBusiness($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            avgPrepTimeMinutes\n            prepTimeOverrideMinutes\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            isOpen\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateOrder($input: CreateOrderInput!) {\n        createOrder(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    isActive\n                    isOpen\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation CreateOrder($input: CreateOrderInput!) {\n        createOrder(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                    isActive\n                    isOpen\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                    createdAt\n                    updatedAt\n                    isOpen\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                    createdAt\n                    updatedAt\n                    isOpen\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    isActive\n                    location {\n                        latitude\n                        longitude\n                        address\n                    }\n                    workingHours {\n                        opensAt\n                        closesAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query UncompletedOrders {\n        uncompletedOrders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query UncompletedOrders {\n        uncompletedOrders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            updatedAt\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n"): (typeof documents)["\n    subscription OrderStatusUpdated($orderId: ID!) {\n        orderStatusUpdated(orderId: $orderId) {\n            id\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    subscription UserOrdersUpdated($input: SubscriptionInput!) {\n        userOrdersUpdated(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    subscription UserOrdersUpdated($input: SubscriptionInput!) {\n        userOrdersUpdated(input: $input) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    imageUrl\n                    businessType\n                    createdAt\n                    updatedAt\n                    isActive\n                    isOpen\n                    location {\n                        address\n                        longitude\n                        latitude\n                    }\n                    workingHours {\n                        closesAt\n                        opensAt\n                    }\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetProducts($businessId: ID!) {\n        products(businessId: $businessId) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query GetProduct($id: ID!) {\n        product(id: $id) {\n            id\n            businessId\n            categoryId\n            subcategoryId\n            name\n            description\n            imageUrl\n            price\n            isOnSale\n            salePrice\n            isAvailable\n            sortOrder\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n    }\n"): (typeof documents)["\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductSubcategoriesByBusiness($businessId: ID!) {\n        productSubcategoriesByBusiness(businessId: $businessId) {\n            id\n            categoryId\n            name\n        }\n    }\n"): (typeof documents)["\n    query ProductSubcategoriesByBusiness($businessId: ID!) {\n        productSubcategoriesByBusiness(businessId: $businessId) {\n            id\n            categoryId\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ValidatePromotions($cart: CartContextInput!, $manualCode: String) {\n        validatePromotions(cart: $cart, manualCode: $manualCode) {\n            totalDiscount\n            freeDeliveryApplied\n            finalSubtotal\n            finalDeliveryPrice\n            finalTotal\n            promotions {\n                id\n                name\n                code\n                type\n                target\n                appliedAmount\n                freeDelivery\n                priority\n            }\n        }\n    }\n"): (typeof documents)["\n    query ValidatePromotions($cart: CartContextInput!, $manualCode: String) {\n        validatePromotions(cart: $cart, manualCode: $manualCode) {\n            totalDiscount\n            freeDeliveryApplied\n            finalSubtotal\n            finalDeliveryPrice\n            finalTotal\n            promotions {\n                id\n                name\n                code\n                type\n                target\n                appliedAmount\n                freeDelivery\n                priority\n            }\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;