import { z } from 'zod';

export const translationSchema = z.object({
    language: z.string(),
    common: z.object({
        ok: z.string(),
        cancel: z.string(),
        save: z.string(),
        delete: z.string(),
        error: z.string(),
        loading: z.string(),
        retry: z.string(),
        search: z.string(),
        noResults: z.string(),
        confirm: z.string(),
        back: z.string(),
        edit: z.string(),
        close: z.string(),
        refresh: z.string(),
    }),
    auth: z.object({
        login: z.object({
            title: z.string(),
            description: z.string(),
            email: z.string(),
            password: z.string(),
            actions: z.object({
                login: z.string(),
                forgotPassword: z.string(),
            }),
            errors: z.object({
                invalid: z.string(),
                required: z.string(),
                unauthorized: z.string(),
            }),
        }),
    }),
    tabs: z.object({
        map: z.string(),
        orders: z.string(),
        dashboard: z.string(),
        more: z.string(),
    }),
    map: z.object({
        title: z.string(),
        filters: z.object({
            all: z.string(),
            orders: z.string(),
            drivers: z.string(),
            businesses: z.string(),
        }),
        orderStatus: z.object({
            all: z.string(),
            pending: z.string(),
            preparing: z.string(),
            ready: z.string(),
            outForDelivery: z.string(),
        }),
        driverStatus: z.object({
            online: z.string(),
            offline: z.string(),
            delivering: z.string(),
        }),
        noDrivers: z.string(),
        noOrders: z.string(),
    }),
    orders: z.object({
        title: z.string(),
        empty: z.string(),
        status: z.object({
            PENDING: z.string(),
            PREPARING: z.string(),
            READY: z.string(),
            OUT_FOR_DELIVERY: z.string(),
            DELIVERED: z.string(),
            CANCELLED: z.string(),
        }),
        detail: z.object({
            title: z.string(),
            customer: z.string(),
            driver: z.string(),
            unassigned: z.string(),
            business: z.string(),
            items: z.string(),
            orderPrice: z.string(),
            deliveryFee: z.string(),
            total: z.string(),
            prepTime: z.string(),
            estimatedReady: z.string(),
            assignDriver: z.string(),
            startPreparing: z.string(),
            markReady: z.string(),
            cancel: z.string(),
        }),
        prepModal: z.object({
            title: z.string(),
            subtitle: z.string(),
            minutes: z.string(),
            start: z.string(),
        }),
    }),
    dashboard: z.object({
        title: z.string(),
        todayOrders: z.string(),
        activeOrders: z.string(),
        revenue: z.string(),
        avgDeliveryTime: z.string(),
        onlineDrivers: z.string(),
        recentOrders: z.string(),
    }),
    more: z.object({
        title: z.string(),
        businesses: z.string(),
        drivers: z.string(),
        users: z.string(),
        promotions: z.string(),
        notifications: z.string(),
        settlements: z.string(),
        storeStatus: z.string(),
        settings: z.string(),
        logout: z.string(),
    }),
    profile: z.object({
        title: z.string(),
        language_toggle: z.string(),
        current_language: z.string(),
        theme: z.string(),
        themeOptions: z.object({
            light: z.string(),
            dark: z.string(),
            system: z.string(),
        }),
    }),
});

export type Translation = z.infer<typeof translationSchema>;
