/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    mutation Login($email: String!, $password: String!) {\n        login(input: { email: $email, password: $password }) {\n            token\n            user {\n                firstName\n                lastName\n                role\n            }\n            message\n        }\n    }\n": typeof types.LoginDocument,
    "\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive\n            \n        }\n    }\n": typeof types.CreateBusinessDocument,
    "\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive   \n        }\n    }\n": typeof types.UpdateBusinessDocument,
    "\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n": typeof types.DeleteBusinessDocument,
    "\n    query Business($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n": typeof types.BusinessDocument,
    "\n    query Businesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.BusinessesDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.UpdateOrderStatusDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n": typeof types.CancelOrderDocument,
    "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrderDocument,
    "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": typeof types.GetOrdersByStatusDocument,
    "\n    mutation CreateProductCategory($input: CreateProductCategoryInput!) {\n        createProductCategory(input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n": typeof types.CreateProductCategoryDocument,
    "\n    mutation UpdateProductCategory(\n        $id: ID!\n        $input: UpdateProductCategoryInput!\n    ) {\n        updateProductCategory(id: $id, input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n": typeof types.UpdateProductCategoryDocument,
    "\n    mutation DeleteProductCategory($id: ID!) {\n        deleteProductCategory(id: $id)\n    }\n": typeof types.DeleteProductCategoryDocument,
    "\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n            isActive\n        }\n    }\n": typeof types.ProductCategoriesDocument,
    "\n    mutation CreateProduct($input: CreateProductInput!) {\n        createProduct(input: $input) {\n            id\n        }\n    }\n": typeof types.CreateProductDocument,
    "\n    mutation UpdateProduct($id: ID!, $input: UpdateProductInput!) {\n        updateProduct(id: $id, input: $input) {\n            id\n        }\n    }\n": typeof types.UpdateProductDocument,
    "\n    mutation DeleteProduct($id: ID!) {\n        deleteProduct(id: $id)\n    }\n": typeof types.DeleteProductDocument,
    "\n    query ProductsAndCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n        products(businessId: $businessId) {\n            id\n            categoryId\n            name\n            description\n            price\n            imageUrl\n            isOnSale\n            salePrice\n            isAvailable\n        }\n    }\n": typeof types.ProductsAndCategoriesDocument,
    "\n  mutation CreateUser(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $role: UserRole!\n    $businessId: ID\n  ) {\n    createUser(\n      input: {\n        email: $email\n        password: $password\n        firstName: $firstName\n        lastName: $lastName\n        role: $role\n        businessId: $businessId\n      }\n    ) {\n      token\n      user {\n        id\n        email\n        firstName\n        lastName\n        role\n        businessId\n      }\n      message\n    }\n  }\n": typeof types.CreateUserDocument,
    "\n  query Users {\n    users {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n": typeof types.UsersDocument,
    "\n  query Drivers {\n    drivers {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n": typeof types.DriversDocument,
};
const documents: Documents = {
    "\n    mutation Login($email: String!, $password: String!) {\n        login(input: { email: $email, password: $password }) {\n            token\n            user {\n                firstName\n                lastName\n                role\n            }\n            message\n        }\n    }\n": types.LoginDocument,
    "\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive\n            \n        }\n    }\n": types.CreateBusinessDocument,
    "\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive   \n        }\n    }\n": types.UpdateBusinessDocument,
    "\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n": types.DeleteBusinessDocument,
    "\n    query Business($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n": types.BusinessDocument,
    "\n    query Businesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.BusinessesDocument,
    "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.UpdateOrderStatusDocument,
    "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n": types.CancelOrderDocument,
    "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrdersDocument,
    "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrderDocument,
    "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n": types.GetOrdersByStatusDocument,
    "\n    mutation CreateProductCategory($input: CreateProductCategoryInput!) {\n        createProductCategory(input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n": types.CreateProductCategoryDocument,
    "\n    mutation UpdateProductCategory(\n        $id: ID!\n        $input: UpdateProductCategoryInput!\n    ) {\n        updateProductCategory(id: $id, input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n": types.UpdateProductCategoryDocument,
    "\n    mutation DeleteProductCategory($id: ID!) {\n        deleteProductCategory(id: $id)\n    }\n": types.DeleteProductCategoryDocument,
    "\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n            isActive\n        }\n    }\n": types.ProductCategoriesDocument,
    "\n    mutation CreateProduct($input: CreateProductInput!) {\n        createProduct(input: $input) {\n            id\n        }\n    }\n": types.CreateProductDocument,
    "\n    mutation UpdateProduct($id: ID!, $input: UpdateProductInput!) {\n        updateProduct(id: $id, input: $input) {\n            id\n        }\n    }\n": types.UpdateProductDocument,
    "\n    mutation DeleteProduct($id: ID!) {\n        deleteProduct(id: $id)\n    }\n": types.DeleteProductDocument,
    "\n    query ProductsAndCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n        products(businessId: $businessId) {\n            id\n            categoryId\n            name\n            description\n            price\n            imageUrl\n            isOnSale\n            salePrice\n            isAvailable\n        }\n    }\n": types.ProductsAndCategoriesDocument,
    "\n  mutation CreateUser(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $role: UserRole!\n    $businessId: ID\n  ) {\n    createUser(\n      input: {\n        email: $email\n        password: $password\n        firstName: $firstName\n        lastName: $lastName\n        role: $role\n        businessId: $businessId\n      }\n    ) {\n      token\n      user {\n        id\n        email\n        firstName\n        lastName\n        role\n        businessId\n      }\n      message\n    }\n  }\n": types.CreateUserDocument,
    "\n  query Users {\n    users {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n": types.UsersDocument,
    "\n  query Drivers {\n    drivers {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n": types.DriversDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation Login($email: String!, $password: String!) {\n        login(input: { email: $email, password: $password }) {\n            token\n            user {\n                firstName\n                lastName\n                role\n            }\n            message\n        }\n    }\n"): (typeof documents)["\n    mutation Login($email: String!, $password: String!) {\n        login(input: { email: $email, password: $password }) {\n            token\n            user {\n                firstName\n                lastName\n                role\n            }\n            message\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive\n            \n        }\n    }\n"): (typeof documents)["\n    mutation CreateBusiness($input: CreateBusinessInput!) {\n        createBusiness(input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive\n            \n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive   \n        }\n    }\n"): (typeof documents)["\n    mutation UpdateBusiness($id: ID!, $input: UpdateBusinessInput!) {\n        updateBusiness(id: $id, input: $input) {\n            id\n            name\n            businessType\n            imageUrl\n            isActive   \n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n"): (typeof documents)["\n    mutation DeleteBusiness($id: ID!) {\n        deleteBusiness(id: $id)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query Business($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    query Business($id: ID!) {\n        business(id: $id) {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query Businesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query Businesses {\n        businesses {\n            id\n            name\n            imageUrl\n            businessType\n            isActive\n            location {\n                latitude\n                longitude\n                address\n            }\n            workingHours {\n                opensAt\n                closesAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateOrderStatus($id: ID!, $status: OrderStatus!) {\n        updateOrderStatus(id: $id, status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n"): (typeof documents)["\n    mutation CancelOrder($id: ID!) {\n        cancelOrder(id: $id) {\n            id\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrders {\n        orders {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrder($id: ID!) {\n        order(id: $id) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetOrdersByStatus($status: OrderStatus!) {\n        ordersByStatus(status: $status) {\n            id\n            orderPrice\n            deliveryPrice\n            totalPrice\n            orderDate\n            status\n            dropOffLocation {\n                latitude\n                longitude\n                address\n            }\n            businesses {\n                business {\n                    id\n                    name\n                    businessType\n                }\n                items {\n                    productId\n                    name\n                    imageUrl\n                    quantity\n                    price\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateProductCategory($input: CreateProductCategoryInput!) {\n        createProductCategory(input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n"): (typeof documents)["\n    mutation CreateProductCategory($input: CreateProductCategoryInput!) {\n        createProductCategory(input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateProductCategory(\n        $id: ID!\n        $input: UpdateProductCategoryInput!\n    ) {\n        updateProductCategory(id: $id, input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateProductCategory(\n        $id: ID!\n        $input: UpdateProductCategoryInput!\n    ) {\n        updateProductCategory(id: $id, input: $input) {\n            id\n            name\n            isActive\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteProductCategory($id: ID!) {\n        deleteProductCategory(id: $id)\n    }\n"): (typeof documents)["\n    mutation DeleteProductCategory($id: ID!) {\n        deleteProductCategory(id: $id)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n            isActive\n        }\n    }\n"): (typeof documents)["\n    query ProductCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n            isActive\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateProduct($input: CreateProductInput!) {\n        createProduct(input: $input) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateProduct($input: CreateProductInput!) {\n        createProduct(input: $input) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateProduct($id: ID!, $input: UpdateProductInput!) {\n        updateProduct(id: $id, input: $input) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateProduct($id: ID!, $input: UpdateProductInput!) {\n        updateProduct(id: $id, input: $input) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteProduct($id: ID!) {\n        deleteProduct(id: $id)\n    }\n"): (typeof documents)["\n    mutation DeleteProduct($id: ID!) {\n        deleteProduct(id: $id)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductsAndCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n        products(businessId: $businessId) {\n            id\n            categoryId\n            name\n            description\n            price\n            imageUrl\n            isOnSale\n            salePrice\n            isAvailable\n        }\n    }\n"): (typeof documents)["\n    query ProductsAndCategories($businessId: ID!) {\n        productCategories(businessId: $businessId) {\n            id\n            name\n        }\n        products(businessId: $businessId) {\n            id\n            categoryId\n            name\n            description\n            price\n            imageUrl\n            isOnSale\n            salePrice\n            isAvailable\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateUser(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $role: UserRole!\n    $businessId: ID\n  ) {\n    createUser(\n      input: {\n        email: $email\n        password: $password\n        firstName: $firstName\n        lastName: $lastName\n        role: $role\n        businessId: $businessId\n      }\n    ) {\n      token\n      user {\n        id\n        email\n        firstName\n        lastName\n        role\n        businessId\n      }\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation CreateUser(\n    $email: String!\n    $password: String!\n    $firstName: String!\n    $lastName: String!\n    $role: UserRole!\n    $businessId: ID\n  ) {\n    createUser(\n      input: {\n        email: $email\n        password: $password\n        firstName: $firstName\n        lastName: $lastName\n        role: $role\n        businessId: $businessId\n      }\n    ) {\n      token\n      user {\n        id\n        email\n        firstName\n        lastName\n        role\n        businessId\n      }\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Users {\n    users {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n"): (typeof documents)["\n  query Users {\n    users {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Drivers {\n    drivers {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n"): (typeof documents)["\n  query Drivers {\n    drivers {\n      id\n      email\n      firstName\n      lastName\n      role\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;