import { z } from 'zod';

export const translationSchema = z.object(
    {
        language: z.string({ message: 'Language name is required to be string' }),
        common: z.object(
            {
                ok: z.string(),
                cancel: z.string(),
                save: z.string(),
                delete: z.string(),
                error: z.string(),
                date: z.string(),
                today: z.string(),
                back: z.string(),
                loading: z.string(),
            },
            { message: 'Common translations must be an object' },
        ),
        auth: z.object(
            {
                login: z.object(
                    {
                        title: z.string(),
                        description: z.string(),
                        actions: z.object(
                            {
                                login: z.string(),
                            },
                            { message: 'Login actions must be an object' },
                        ),
                    },
                    { message: 'Login translations must be an object' },
                ),
            },
            { message: 'Auth translations must be an object' },
        ),
        tabs: z.object(
            {
                home: z.string(),
                map: z.string(),
                earnings: z.string(),
                messages: z.string(),
                profile: z.string(),
            },
            { message: 'Tabs translations must be an object' },
        ),
        home: z.object(
            {
                greeting_morning: z.string(),
                greeting_afternoon: z.string(),
                greeting_evening: z.string(),
                online: z.string(),
                offline: z.string(),
                signal_good: z.string(),
                signal_weak: z.string(),
                signal_lost: z.string(),
                dispatch_mode_title: z.string(),
                dispatch_mode_sub: z.string(),
                earnings_today: z.string(),
                your_take: z.string(),
                gross: z.string(),
                commission: z.string(),
                deducted: z.string(),
                delivered_today: z.string(),
                avg_per_delivery: z.string(),
                active_orders: z.string(),
                no_active_orders: z.string(),
                at_max_capacity: z.string(),
                slots_available: z.string(),
                slot_available: z.string(),
                heartbeat: z.string(),
                check_signal: z.string(),
                error_update_status: z.string(),
            },
            { message: 'Home translations must be an object' },
        ),
        map: z.object(
            {
                status_pending: z.string(),
                status_preparing: z.string(),
                status_ready: z.string(),
                status_delivering: z.string(),
            },
            { message: 'Map translations must be an object' },
        ),
        earnings: z.object(
            {
                title: z.string(),
                subtitle: z.string(),
                period_week: z.string(),
                period_month: z.string(),
                period_last_month: z.string(),
                period_all: z.string(),
                net_earnings: z.string(),
                delivery: z.string(),
                deliveries: z.string(),
                paid: z.string(),
                pending: z.string(),
                unsettled: z.string(),
                pending_balance: z.string(),
                platform_owes_you: z.string(),
                you_owe_platform: z.string(),
                net_pending: z.string(),
                deliveries_list: z.string(),
                no_earnings_title: z.string(),
                no_earnings_sub: z.string(),
                commission: z.string(),
                paid_on: z.string(),
            },
            { message: 'Earnings translations must be an object' },
        ),
        messages: z.object(
            {
                type_message: z.string(),
                type_warning: z.string(),
                type_urgent: z.string(),
                today: z.string(),
                yesterday: z.string(),
                placeholder: z.string(),
                send: z.string(),
                no_messages_title: z.string(),
                no_messages_sub: z.string(),
                clear: z.string(),
                clear_confirm_title: z.string(),
                clear_confirm_message: z.string(),
            },
            { message: 'Messages translations must be an object' },
        ),
        profile: z.object(
            {
                title: z.string(),
                driver_badge: z.string(),
                language_section: z.string(),
                language_toggle: z.string(),
                current_language: z.string(),
                logout: z.string(),
                logout_title: z.string(),
                logout_confirm: z.string(),
                logout_error: z.string(),
            },
            { message: 'Profile translations must be an object' },
        ),
    },
    { message: 'Translation schema must be an object' },
);

export type Translation = z.infer<typeof translationSchema>;
