import { z } from 'zod';

export const translationSchema = z.object(
    {
        language: z.string({ message: 'Language name is required to be string' }),
        common: z.object(
            {
                ok: z.string(),
                cancel: z.string(),
                save: z.string(),
                delete: z.string(),
                error: z.string(),
                date: z.string(),
                today: z.string(),
                back: z.string(),
                loading: z.string(),
            },
            { message: 'Common translations must be an object' },
        ),
        auth: z.object(
            {
                login: z.object(
                    {
                        title: z.string(),
                        description: z.string(),
                        actions: z.object(
                            {
                                login: z.string(),
                            },
                            { message: 'Login actions must be an object' },
                        ),
                    },
                    { message: 'Login translations must be an object' },
                ),
            },
            { message: 'Auth translations must be an object' },
        ),
        tabs: z.object(
            {
                home: z.string(),
                map: z.string(),
                earnings: z.string(),
                messages: z.string(),
                profile: z.string(),
            },
            { message: 'Tabs translations must be an object' },
        ),
        home: z.object(
            {
                greeting_morning: z.string(),
                greeting_afternoon: z.string(),
                greeting_evening: z.string(),
                online: z.string(),
                offline: z.string(),
                signal_good: z.string(),
                signal_weak: z.string(),
                signal_lost: z.string(),
                dispatch_mode_title: z.string(),
                dispatch_mode_sub: z.string(),
                earnings_today: z.string(),
                your_take: z.string(),
                gross: z.string(),
                commission: z.string(),
                deducted: z.string(),
                delivered_today: z.string(),
                avg_per_delivery: z.string(),
                active_orders: z.string(),
                no_active_orders: z.string(),
                at_max_capacity: z.string(),
                slots_available: z.string(),
                slot_available: z.string(),
                heartbeat: z.string(),
                check_signal: z.string(),
                error_update_status: z.string(),
            },
            { message: 'Home translations must be an object' },
        ),
        map: z.object(
            {
                status_pending: z.string(),
                status_preparing: z.string(),
                status_ready: z.string(),
                status_delivering: z.string(),
            },
            { message: 'Map translations must be an object' },
        ),
        earnings: z.object(
            {
                title: z.string(),
                subtitle: z.string(),
                period_today: z.string().optional(),
                period_week: z.string(),
                period_month: z.string(),
                period_last_month: z.string(),
                period_all: z.string(),
                net_earnings: z.string(),
                delivery: z.string(),
                deliveries: z.string(),
                paid: z.string(),
                pending: z.string(),
                unsettled: z.string(),
                pending_balance: z.string(),
                platform_owes_you: z.string(),
                you_owe_platform: z.string(),
                net_pending: z.string(),
                deliveries_list: z.string(),
                no_earnings_title: z.string(),
                no_earnings_sub: z.string(),
                commission: z.string(),
                paid_on: z.string(),
                stock_remittance: z.string().optional(),
                stock_remittance_sub: z.string().optional(),
                accept: z.string().optional(),
                accept_title: z.string().optional(),
                accept_text: z.string().optional(),
                reject: z.string().optional(),
                reject_title: z.string().optional(),
                reject_placeholder: z.string().optional(),
                reject_submit: z.string().optional(),
                dispute: z.string().optional(),
                dispute_title: z.string().optional(),
                dispute_placeholder: z.string().optional(),
                dispute_submit: z.string().optional(),
                awaiting_response: z.string().optional(),
                settlement_requests: z.string().optional(),
                settlement_breakdown: z.string().optional(),
                you_receive: z.string().optional(),
                markup: z.string().optional(),
                priority: z.string().optional(),
                delivery_fee: z.string().optional(),
                tip_label: z.string().optional(),
                catalog_label: z.string().optional(),
                explain_markup: z.string().optional(),
                explain_stock: z.string().optional(),
                explain_delivery: z.string().optional(),
                explain_platform: z.string().optional(),
                explain_promo: z.string().optional(),
                explain_tip: z.string().optional(),
                explain_catalog: z.string().optional(),
                step_collected: z.string().optional(),
                step_collected_hint: z.string().optional(),
                step_deductions: z.string().optional(),
                step_deductions_hint: z.string().optional(),
                step_additions: z.string().optional(),
                step_additions_hint: z.string().optional(),
                take_home: z.string().optional(),
                take_home_formula: z.string().optional(),
                load_more: z.string().optional(),
                delivery_details: z.string().optional(),
                status: z.string().optional(),
                net: z.string().optional(),
                order_info: z.string().optional(),
                payment_method: z.string().optional(),
                cash_payment: z.string().optional(),
                prepaid_payment: z.string().optional(),
                order_date: z.string().optional(),
                timeline: z.string().optional(),
                assigned: z.string().optional(),
                preparing: z.string().optional(),
                ready: z.string().optional(),
                picked_up: z.string().optional(),
                delivered: z.string().optional(),
                pricing: z.string().optional(),
                items_total: z.string().optional(),
                total: z.string().optional(),
                financial_breakdown: z.string().optional(),
                collect_from_customer: z.string().optional(),
                remit_to_platform: z.string().optional(),
                tip_included: z.string().optional(),
                your_earnings: z.string().optional(),
            },
            { message: 'Earnings translations must be an object' },
        ),
        messages: z.object(
            {
                type_message: z.string(),
                type_warning: z.string(),
                type_urgent: z.string(),
                today: z.string(),
                yesterday: z.string(),
                placeholder: z.string(),
                send: z.string(),
                no_messages_title: z.string(),
                no_messages_sub: z.string(),
                clear: z.string(),
                clear_confirm_title: z.string(),
                clear_confirm_message: z.string(),
            },
            { message: 'Messages translations must be an object' },
        ),
        profile: z.object(
            {
                title: z.string(),
                driver_badge: z.string(),
                language_section: z.string(),
                language_toggle: z.string(),
                current_language: z.string(),
                logout: z.string(),
                logout_title: z.string(),
                logout_confirm: z.string(),
                logout_error: z.string(),
            },
            { message: 'Profile translations must be an object' },
        ),
        orderAccept: z.object(
            {
                new_order: z.string(),
                you_earn: z.string(),
                food_status: z.string(),
                dropoff: z.string(),
                distance: z.string(),
                total_route: z.string(),
                ready_now: z.string(),
                ready_in: z.string(),
                almost_ready: z.string(),
                preparing: z.string(),
                item: z.string(),
                items: z.string(),
                more: z.string(),
                accept_order: z.string(),
                accept_navigate: z.string(),
                skip: z.string(),
                close: z.string(),
                order_taken: z.string(),
                taken_sub: z.string(),
                taken_hint: z.string(),
                see_map: z.string(),
            },
            { message: 'OrderAccept translations must be an object' },
        ),
        orderPool: z.object(
            {
                available_orders: z.string(),
                no_orders_title: z.string(),
                no_orders_sub: z.string(),
                earn: z.string(),
                ready_now: z.string(),
                almost_ready: z.string(),
                preparing: z.string(),
                min: z.string(),
                item: z.string(),
                items: z.string(),
                accept: z.string(),
                accept_go: z.string(),
                see_map: z.string(),
            },
            { message: 'OrderPool translations must be an object' },
        ),
        pickup: z.object(
            {
                arrived_at_pickup: z.string(),
                slide_confirm: z.string(),
                cancel_navigation: z.string(),
                food_almost_ready: z.string(),
                food_ready_in: z.string(),
                min: z.string(),
                to_dropoff: z.string(),
                on_your_way: z.string(),
            },
            { message: 'Pickup translations must be an object' },
        ),
        delivery: z.object(
            {
                arrived_at_dropoff: z.string(),
                im_here: z.string(),
                notified: z.string(),
                slide_confirm: z.string(),
                customer_not_here: z.string(),
                ping_again: z.string(),
                ping: z.string(),
                ping_time: z.string(),
                cancel_order: z.string(),
                cancel_time: z.string(),
                subtotal: z.string(),
                delivery_fee: z.string(),
                total: z.string(),
                select_reason: z.string(),
                slide_cancel: z.string(),
                select_reason_first: z.string(),
                reason_not_responding: z.string(),
                reason_wrong_address: z.string(),
                reason_refused: z.string(),
                reason_safety: z.string(),
                reason_other: z.string(),
            },
            { message: 'Delivery translations must be an object' },
        ),
        navigation: z.object(
            {
                waiting_for_gps: z.string(),
                no_active_order: z.string(),
                loading_navigation: z.string(),
                order_reassigned: z.string(),
                order_reassigned_msg: z.string(),
                call_customer: z.string(),
                new_order_assigned: z.string(),
                less_than_one_min: z.string(),
                min: z.string(),
                to_pickup: z.string(),
                to_dropoff: z.string(),
                preparing_ellipsis: z.string(),
                almost_ready: z.string(),
                ready_in: z.string(),
                delivered: z.string(),
                delivery_earned: z.string(),
                dispatcher: z.string(),
                status_update_failed: z.string(),
            },
            { message: 'Navigation translations must be an object' },
        ),
        drive: z.object(
            {
                navigate_to_pickup: z.string(),
                arrived: z.string(),
                pickup: z.string(),
                resume_navigation: z.string(),
                swipe_hint: z.string(),
                min_to_drop: z.string(),
                min_to_pickup: z.string(),
                almost_ready: z.string(),
                ready_min: z.string(),
                status_update_failed: z.string(),
                nav_choice_title: z.string(),
                nav_choice_inapp: z.string(),
                nav_choice_gmaps: z.string(),
                nav_choice_cancel: z.string(),
                from_stock_label: z.string(),
                from_market_label: z.string(),
            },
            { message: 'Drive translations must be an object' },
        ),
    },
    { message: 'Translation schema must be an object' },
);

export type Translation = z.infer<typeof translationSchema>;
