/**
 * Shared GraphQL query/mutation result types for the web-customer app.
 *
 * These mirror the shape of the fields selected in each GraphQL operation
 * defined in src/graphql/operations/.  They are NOT generated by codegen —
 * update them manually when query selections change.
 */

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

export interface LoginResult {
    token: string;
    refreshToken?: string | null;
    user: {
        id: string;
        email: string;
        firstName: string | null;
        lastName: string | null;
        signupStep: string | null;
        emailVerified: boolean;
        phoneVerified: boolean;
        phoneNumber: string | null;
        role: string | null;
        preferredLanguage: string | null;
    };
    message?: string | null;
}

export interface MeResult {
    id: string;
    email: string;
    firstName: string | null;
    lastName: string | null;
    signupStep: string | null;
    emailVerified: boolean;
    phoneVerified: boolean;
    phoneNumber: string | null;
    address: string | null;
    role: string | null;
    preferredLanguage: string | null;
    emailOptOut: boolean | null;
}

export interface SignupStepResult {
    userId: string;
    currentStep: string;
    message?: string | null;
}

export interface InitiateSignupResult {
    token: string;
    user: LoginResult["user"];
    message?: string | null;
}

// ---------------------------------------------------------------------------
// Businesses
// ---------------------------------------------------------------------------

export interface ActivePromotion {
    id: string;
    name: string;
    type: string;
    discountValue: number;
    spendThreshold?: number | null;
}

export interface WorkingHours {
    opensAt: string | null;
    closesAt: string | null;
}

export interface ScheduleEntry {
    dayOfWeek: number;
    opensAt: string | null;
    closesAt: string | null;
}

export interface GqlBusiness {
    id: string;
    name: string;
    description: string | null;
    imageUrl: string | null;
    businessType: string | null;
    isActive: boolean;
    avgPrepTimeMinutes: number | null;
    prepTimeOverrideMinutes: number | null;
    isTemporarilyClosed: boolean;
    temporaryClosureReason: string | null;
    latitude: number | null;
    longitude: number | null;
    address: string | null;
    isOpen: boolean;
    minOrderAmount: number | null;
    ratingAverage?: number | null;
    ratingCount?: number | null;
    location?: { latitude: number; longitude: number; address: string | null } | null;
    activePromotion: ActivePromotion | null;
    workingHours: WorkingHours | null;
    schedule: ScheduleEntry[] | null;
    createdAt: string;
    updatedAt: string;
}

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

export interface GqlVariant {
    id: string;
    name: string;
    imageUrl: string | null;
    price: number;
    effectivePrice: number;
    markupPrice: number;
    nightMarkedupPrice: number;
    isOnSale: boolean;
    saleDiscountPercentage: number;
    isAvailable: boolean;
}

export interface GqlOption {
    id: string;
    name: string;
    extraPrice: number;
    displayOrder: number | null;
    linkedProductId: string | null;
    linkedProduct: GqlProduct | null;
}

export interface GqlOptionGroup {
    id: string;
    name: string;
    minSelections: number | null;
    maxSelections: number | null;
    displayOrder: number | null;
    options: GqlOption[] | null;
}

export interface GqlProduct {
    id: string;
    name: string;
    description?: string | null;
    imageUrl: string | null;
    basePrice: number;
    price?: number;
    effectivePrice?: number;
    markupPrice?: number;
    nightMarkedupPrice?: number;
    isOffer: boolean;
    isAvailable?: boolean;
    isOnSale?: boolean;
    saleDiscountPercentage?: number;
    hasOptionGroups: boolean;
    businessId?: string;
    categoryId?: string | null;
    subcategoryId?: string | null;
    sortOrder?: number | null;
    variantGroupId?: string | null;
    variants: GqlVariant[];
    optionGroups?: GqlOptionGroup[] | null;
    product?: Omit<GqlProduct, 'product'>;
}

export interface GqlProductCategory {
    id: string;
    name: string;
}

export interface GqlProductSubcategory {
    id: string;
    categoryId: string;
    name: string;
}

// ---------------------------------------------------------------------------
// Addresses
// ---------------------------------------------------------------------------

export interface GqlAddress {
    id: string;
    latitude: number;
    longitude: number;
    addressName: string | null;
    displayName: string | null;
    priority: number | null;
    createdAt: string;
}

// ---------------------------------------------------------------------------
// Orders
// ---------------------------------------------------------------------------

export interface GqlOrderItem {
    id?: string;
    name: string;
    quantity: number;
    price: number;
    unitPrice?: number;
    productId?: string;
    imageUrl?: string | null;
    selectedOptions?: { name: string; priceAtOrder: number }[] | null;
    childItems?: { name: string }[] | null;
}

export interface GqlOrderBusiness {
    business: {
        id: string;
        name: string;
        imageUrl: string | null;
        businessType?: string | null;
        location?: { latitude: number; longitude: number; address?: string | null } | null;
    } | null;
    items: GqlOrderItem[];
}

export interface GqlOrder {
    id: string;
    displayId: string | null;
    orderNumber?: string | null;
    userId: string;
    orderPrice: number;
    deliveryPrice: number;
    totalPrice: number;
    subtotal?: number;
    orderDate: string;
    createdAt?: string;
    updatedAt: string;
    status: string;
    approvalReasons: string[] | null;
    preparationMinutes: number | null;
    estimatedReadyAt: string | null;
    preparingAt: string | null;
    readyAt: string | null;
    outForDeliveryAt: string | null;
    deliveredAt: string | null;
    dropOffLocation: { lat: number; lng: number; latitude?: number; longitude?: number; address: string | null } | null;
    driver: {
        id: string;
        firstName: string | null;
        lastName: string | null;
        phoneNumber: string | null;
        imageUrl: string | null;
        driverConnection?: { remainingEtaSeconds?: number | null; etaUpdatedAt?: string | null } | null;
        driverLocation?: { lat: number; lng: number } | null;
    } | null;
    driverLocation: { lat: number; lng: number; address: string | null } | null;
    driverLocationUpdatedAt: string | null;
    driverConnection: string | null;
    businesses: GqlOrderBusiness[];
    reviewSubmitted?: boolean;
    prioritySurcharge?: number | null;
    discountAmount?: number | null;
    // Single-order query extras
    driverNotes?: string | null;
    pickupLocations?: { lat: number; lng: number; latitude?: number; longitude?: number; address: string | null }[] | null;
    originalPrice?: number | null;
    paymentCollection?: string | null;
    orderPromotions?: GqlOrderPromotion[] | null;
}

export interface GqlOrderPromotion {
    id: string;
    promotionId: string;
    appliesTo: string;
    discountAmount: number;
    promoCode: string | null;
}

export interface GqlOrdersResult {
    totalCount: number;
    orders: GqlOrder[];
}

export interface GqlDriverLiveTracking {
    orderId: string;
    driverId: string;
    latitude: number;
    longitude: number;
    navigationPhase: string | null;
    remainingEtaSeconds: number | null;
    etaUpdatedAt: string | null;
}

// ---------------------------------------------------------------------------
// Promotions
// ---------------------------------------------------------------------------

export interface GqlPromotion {
    id: string;
    name: string;
    code: string | null;
    type: string;
    target: string;
    appliedAmount: number | null;
    freeDelivery: boolean;
    priority: number | null;
    description?: string | null;
    discountValue?: number | null;
    spendThreshold?: number | null;
    eligibleBusinessIds?: string[] | null;
}

export interface GqlValidationResult {
    totalDiscount: number;
    freeDeliveryApplied: boolean;
    finalBasePrice: number;
    finalTotalPrice: number;
    applicablePromotions: GqlPromotion[];
}

// ---------------------------------------------------------------------------
// Delivery zones
// ---------------------------------------------------------------------------

export interface GqlDeliveryZone {
    id: string;
    name: string;
    polygon: { lat: number; lng: number }[];
    isActive: boolean;
    isServiceZone: boolean;
}

// ---------------------------------------------------------------------------
// Banners
// ---------------------------------------------------------------------------

export interface GqlBanner {
    id: string;
    title: string | null;
    subtitle: string | null;
    imageUrl: string | null;
    mediaType: string | null;
    linkType: string | null;
    linkTarget: string | null;
    sortOrder: number | null;
    isActive: boolean;
}

// ---------------------------------------------------------------------------
// Mapbox search result (not GraphQL but used in AddressPickerMap)
// ---------------------------------------------------------------------------

export interface MapboxFeature {
    id: string;
    text?: string;
    place_name: string;
    center: [number, number];
    context?: { text: string }[];
}
